apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kudos-board
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yatingambhir85/kudos-board
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: kudos-board
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
