name: Code Dependency Check

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install ESLint in Root
        run: npm install --save-dev eslint @eslint/js
      - name: Install & Run Backend Linter
        run: |
          cd backend/
          npm ci
          cd ..
          npx eslint "backend/**/*.js"
      - name: Install & Run Frontend Linter
        run: |
         cd frontend/
         npm ci
         cd ..
         npx eslint "frontend/**/*.js"
      - name: Run Audit Fix
        run: |
          cd backend && npm audit fix --package-lock-only || true
          cd frontend && npm audit fix --package-lock-only || true
