name: Dockerfile Lint

on: 
  workflow_dispatch:

jobs:
  dockerfile-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Dockerfile Lint - Backend
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/Dockerfile
      - name: Dockerfile Lint - Frontend
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: frontend/Dockerfile
